/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
public class App {
    public static void main(String[] args) {
        // This liberary helps us to make HTTP requests
        OkHttpClient client = new OkHttpClient();
        String url = "https://jsonplaceholder.typicode.com/todos/1";
        Request request = new Request.Builder().url(url).build();

        try(Response response = client.newCall(request).execute()) {
            if (!response.isSuccessful()) {
                System.out.println("Request failed with status code: " + response.code());
            }
            System.out.println("Response: " + response.body().string());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
